# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-07 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urlographer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmap',
            name='canonical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canonical_childs', to='urlographer.URLMap'),
        ),
    ]
