# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-27 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urlographer', '0002_urlmap_canonical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmap',
            name='canonical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='urlographer.URLMap'),
        ),
    ]
